services:
  - type: web
    name: devdoc-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
    
    # Persistent disk for uploads
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 